name: SHE Photography CA
favicon: null
layout_spectrum: 0.80306
typography_spectrum: 0.67983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cc247c'
    - '#6d6b6c'
    - '#000003'
    - '#f8b3c2'
  brandStrength: 0.34551961440593004
  lightness: 0.4888106784783304
  saturation: 0.9396220354828984
  rhythmicContrast: 0.8303035858552903
purpose: []
